name: Workflow to test the webshop using Docker Compose and matrix

on:
  push:
    branches:
      - master

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Read browsers JSON file and set output
      id: set-matrix
      run: |
        content=$(cat ./browsers.json)
        echo "matrix={\"browsers\": $content}" >> $GITHUB_ENV

  run-tests:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set BROWSER_ENV variable
      run: echo "BROWSER_ENV=${{ matrix.browsers }}" >> $GITHUB_ENV

    - name: Run Docker Compose
      run: |
        sed -i "s/- BROWSER=Chrome/- BROWSER=${{ env.BROWSER_ENV }}/g" docker-compose.yml
        docker-compose up -d web db
        docker-compose up robot

    - name: Copy results
      if: always()
      run: |
        docker cp robot_framework_container:/results ./results

    - name: Remove container
      if: always()
      run: |
        docker-compose down

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.browsers }}
        path: ./results
